services:
    rabbitmq:
        image: rabbitmq:3-management
        ports: 
            - "0.0.0.0:15672:15672"
            - "0.0.0.0:5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=achausername
            - RABBITMQ_DEFAULT_PASS=strongpassword
