services:
    rabbitmq:
        image: rabbitmq:3-management
        # network_mode: host
        networks:
            - potentiometer-network
        ports: 
            - "15672:15672"
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=achausername
            - RABBITMQ_DEFAULT_PASS=strongpassword
networks:
    potentiometer-network:
        name: potentiometer-network
version: '3.5'
